### PR TITLE
Note explicit support for Python 3.5

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by felixonmars** [comment]
Looks like I was opening this too fast. The error is harder to fix than I expected, as the parser will never raise an error in Python 3.5 if I understand it correctly...

**Comment by mgedmin** [comment]
Yeah: https://docs.python.org/3.3/library/html.parser.html#html.parser.HTMLParseError

**Comment by mgedmin** [comment]
HTMLParseError is only used as a base class for new exceptions defined in zope.tal.htmltalparser.

Suggestion:
```python
try:
    # Python 2.x
    from HTMLParser import HTMLParser, HTMLParseError
except ImportError:
    # Python 3.x
    from html.parser import HTMLParser
    try:
        from html.parser import HTMLParseError
    except ImportError:
        # Python 3.5 removed it, but we need it as a base class
        # so here's a copy taken from Python 3.4:
        class HTMLParseError(Exception):
            def __init__(self, msg, position=(None, None)):
                assert msg
                self.msg = msg
                self.lineno = position[0]
                self.offset = position[1]

            def __str__(self):
                result = self.msg
                if self.lineno is not None:
                    result = result + ", at line %d" % self.lineno
                if self.offset is not None:
                    result = result + ", column %d" % (self.offset + 1)
                return result
```

**Comment by felixonmars** [comment]
Updated accordingly, thanks! I originally thought it rely on the standard library to raise the exception :P

**Pull request merged**
