### PR TITLE
Fix unicode issue

### PR DESCRIPTION
**Pull request by gyst**
As reported in https://github.com/collective/i18ndude/pull/48

### CODE REVIEW

**Comment by jamadden** [comment]
That file is, sadly, largly untested. But there are some existing tests that are using `POTALInterpreter`, which seems to have the only function that uses `unicode`. Would it be possible to add a test case that's fixed by this change?

**Comment by mauritsvanrees** [comment]
I added a test on the PR branch for good measure. This exercises the fix from Guido.
Apart from that, it is not a very useful test. `i18ndude` uses this method, but only indirectly so it is not interested in the what is returned by the method: the important thing is that something is added to the translation catalog.

**Comment by mauritsvanrees** [comment]
Ah, thanks for adding the changelog entry. And for the review. I will merge.

**Comment by icemac** [comment]
Thank you to everyone who worked on this issue. I released the fix as 4.3.1 to PyPI.

**Pull request merged**
